Use the new keepUpright parameter in OpenLayers
openlayers/ol-mapbox-style pull request #1208
Opened 2024-10-20 21:50 UTC by leyan

Until now, the `text-keep-upright` parameter in the Mapbox Style specification was ignored, as OpenLayers was automatically keeping the labels upright and did not expose an option to control it. Now that the `keepUpright` parameter is available on `ol/style/Text`, this PR uses it to cover `text-keep-upright`.

This is a follow-up to #1206 now that the cleaner solution is available.

2024-10-21 08:06 UTC, ahocevar requested changes

2024-10-21 08:06 UTC, ahocevar commented on src/stylefunction.js
> +          text.setKeepUpright(keepUpright);
For compatibility with older OpenLayers versions, this should be wrapped in an if-block:
```js
if (typeof text.setKeepUpright === 'function') {
  // ...
}

2024-10-24 21:50 UTC, leyan commented
@ahocevar Should I create a test for this parameter? if so, how should I go about it? I saw there are quite a lot of tests but I am not sure about how to add one.

2024-11-12 21:48 UTC, ahocevar approved these changes
Thanks, @leyan

2024-11-12 21:50 UTC, merged